# Generated by Django 5.2.6 on 2025-09-16 05:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('shoes', 'Shoes'), ('jersey', 'Jersey'), ('equipment', 'Equipment'), ('accessories', 'Accessories'), ('training', 'Training')], default='training', max_length=20)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
    ]
